[package]
name = "remote_server"
description = "Daemon used for remote editing"
edition = "2021"
version = "0.1.0"
publish = false
license = "GPL-3.0-or-later"

[lints]
workspace = true

[lib]
path = "src/remote_server.rs"
doctest = false

[[bin]]
name = "remote_server"

[features]
default = []
test-support = ["fs/test-support"]

[dependencies]
anyhow.workspace = true
collections.workspace = true
env_logger.workspace = true
fs.workspace = true
futures.workspace = true
gpui.workspace = true
log.workspace = true
project.workspace = true
remote.workspace = true
rpc.workspace = true
settings.workspace = true
smol.workspace = true
text.workspace = true
worktree.workspace = true

[dev-dependencies]
gpui = { workspace = true, features = ["test-support"] }
fs = { workspace = true, features = ["test-support"] }
